<title>Contacts</title>

<!-- custom style -->
<link rel="stylesheet" type="text/css" href="css/styles.css">

<!-- font awesome -->
<link rel="stylesheet" type="text/css" href="css/font-awesome.min.css">

<!-- DataTables CSS -->
<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.5/css/jquery.dataTables.css">

<!-- jQuery -->
<script type="text/javascript" charset="utf8" src="//code.jquery.com/jquery-1.10.2.min.js"></script>

<!-- tynymce -->
<script src="//tinymce.cachefly.net/4.1/tinymce.min.js"></script>

<!-- Custom js -->
<script type="text/javascript" charset="utf8" src="js/custom.js"></script>

  
<!-- DataTables -->
<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.5/js/jquery.dataTables.js"></script>